name: Python Test

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Allure
      run: |
        sudo apt-get install allure
    - name: Test with pytest
      run: |
        pytest -m SMOKE --alluredir=/tmp/allure-results
    - name: Generate Allure report
      run: |
        allure generate /tmp/allure-results -o allure-report --clean
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report