name: Python Test

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Java 11 (Required for Allure)
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Use Adoptium Temurin distribution
        java-version: '11'
    
    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
        sudo tar -zxvf allure-commandline-2.17.2.tgz -C /opt/

    - name: Check Allure Version Directly
      run: /opt/allure-2.17.2/bin/allure --version

    - name: Test with pytest and generate results for Allure
      run: |
        pytest -m SMOKE --alluredir=/tmp/allure-results
    
    - name: Generate Allure report
      run: |
        allure generate /tmp/allure-results -o allure-report --clean
    
    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report